### ISSUE TITLE
Proposal of new API field: metadata

### ISSUE THREAD

**Issue by joaoavf** [DefiLlama/yield-server#309] opened 2022-09-07 14:47 UTC
Hey I am currently experimenting with consuming `https://yields.llama.fi/pools` for APY data. I have/had some working version if it live on `https://dev.defibasket.org/create`. Unfortunately using UUIDs instead of poolIds was a breaking change for me :(

I think UUIDs make a lot of sense to standardize `poolIds`, but I am currently in need to make a link between the assets we have on our database to the assets I consume from the API, and I am currently unable to do so based only on UUIDs.

The easiest solution that comes to mind is to keep the old id in there somehow as `metadata` or something like that.

Another suggestion is to create an object to contain such non-standardized data for protocol specific parameters: `{address: ...., poolId: ....}`

`metadata` can be set to the old poolId as default, but can be slowly and individually upgraded to a new and better organized format.

I am pretty available to work on this, and open to other solutions as well. 

Thanks for the great work!!

**Comment by vrtnd** [comment] 2022-09-08 12:00
Hi, thanks for pointing to the issues.
@slasher125, wdyt?

**Comment by 0xngmi** [comment] 2022-09-08 14:13
sorry about this, working on a new endpoint but in the meantime you can use https://yields.llama.fi/distinctID for a mapping of old ids to new ids

**Comment by 0xngmi** [comment] 2022-09-08 21:21
New endpoint: https://yields.llama.fi/poolsOld

**Comment by slasher125** [comment] 2022-09-09 03:11
had a chat with @joaoavf on discord. will think how to best address the metadata idea, its very related to the receiptToken ting we were discussing. coming back to this early next week :)

**Comment by joaoavf** [comment] 2022-09-09 03:21
Just to give an update on my side. Thanks for the quick response @0xngmi, @slasher125 and @vrtnd 🙏 

Issue is solved on my end, currently using [https://yields.llama.fi/distinctID](https://yields.llama.fi/distinctID)

Let me know if I can be helpful. Happy to give details on our use case and contribute with code.

**Comment by Amurmurmur** [comment] 2022-09-09 10:30
> New endpoint: https://yields.llama.fi/poolsOld

This endpoint, gets redirected to https://defillama-datasets.s3.eu-central-1.amazonaws.com/temp/yields-poolsOld.json
It breaks when fetching in the JS client it throws CORS error

When quering from the browser the https://yields.llama.fi/pools doesnt do it.

**Comment by 0xngmi** [comment] 2022-09-11 01:53
@Amurmurmur ty for letting us know. I've updated the endpoint to attach appropriate CORS headers and also improved caching, so now requests should be significantly faster.

Please let me know if anything else needs to be changed

**Comment by Amurmurmur** [comment] 2022-09-26 13:47
@0xngmi Thank you for a quick respond.
Still redirecting to:
https://defillama-datasets.s3.eu-central-1.amazonaws.com/temp/yields-poolsOld.json

**Comment by 0xngmi** [comment] 2023-04-29 15:53
the redirect is working as intended, lambdas cant return more than 6MB of data so instead we store the response in s3 and return a redirect to it

**Comment by 0xngmi** [comment] 2023-06-14 22:02
with the recent changes in our infra now we improved this and we no longer have a redirect, you should get the data right away from the response

closing this issue too since the problem got solved a while ago

**Closed by 0xngmi** 2023-06-14 22:02 UTC
